name: Scan Docker Image
on: push
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Trivy
      run: |
        sudo apt-get update
        sudo apt-get install wget
        wget https://github.com/aquasecurity/trivy/releases/download/v0.34.0/trivy_0.34.0_Linux-64bit.deb
        sudo dpkg -i trivy_0.34.0_Linux-64bit.deb
    - name: Scan Docker Image
      run: trivy image app
