name: Docker Image Build and Trivy Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image to Docker Hub only
      - name: Build and push Docker image to Docker Hub
        env:
          IMAGE_NAME: 007kumar/scan-app
        run: |
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest

      # Install Trivy
      - name: Install Trivy
        run: |
          sudo apt update
          sudo apt install -y curl gnupg lsb-release
          curl -fsSL https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo tee /etc/apt/trusted.gpg.d/trivy.asc
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt update
          sudo apt install -y trivy
          trivy --version
          
      # Run Trivy Scan on Docker Hub Image
      - name: Run Trivy Scan on Docker Hub Image
        run: trivy image 007kumar/scan-app:latest

      # Fail workflow if vulnerabilities are found
      - name: Fail workflow if vulnerabilities are found
        run: |
          trivy image --exit-code 1 --severity CRITICAL,HIGH 007kumar/scan-app:latest
