name: Docker Image Build and Trivy Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image to Docker Hub only
      - name: Build and push Docker image to Docker Hub
        env:
          IMAGE_NAME: 007kumar/trivyscan
        run: |
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest

      # Install Trivy
      - name: Install Trivy
        run: |
          sudo apt update
          sudo apt install -y curl gnupg lsb-release
          curl -fsSL https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo tee /etc/apt/trusted.gpg.d/trivy.asc
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt update
          sudo apt install -y trivy
          trivy --version
          
      # Run Trivy Scan on Docker Hub Image
      - name: Run Trivy Scan on Docker Hub Image
        run: trivy image 007kumar/trivyscan:latest
          trivy image ***/trivyscan:latest --severity HIGH,CRITICAL --format json -o trivy_report.json
          #trivy image --severity HIGH,CRITICAL --format json -o trivy_report.json 007kumar/trivyscan:latest
          #trivy image --severity HIGH,CRITICAL --format template --template '@contrib/html.tpl' -o trivy_report.html 007kumar/trivyscan:latest

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: my-output-folder/
