name: Docker Image Build and Trivy Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configure AWS Credential
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      # Login to AWS ECR
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image to both Docker Hub & AWS ECR
      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_NAME: 007kumar/scan-app
        run: |
          docker build -t $ECR_REGISTRY/$IMAGE_NAME:latest .
          docker push $ECR_REGISTRY/$IMAGE_NAME:latest
          docker build -t 007kumar/scan-app:latest .
          docker push 007kumar/scan-app:latest

      # Install Trivy
      - name: Install Trivy
        run: |
          sudo apt update
          sudo apt install wget -y
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_Linux-64bit.tar.gz
          tar -xzf trivy_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/
          trivy --version

      # Run Trivy Scan on Docker Hub Image
      - name: Run Trivy Scan on Docker Hub Image
        run: trivy image 007kumar/scan-app:latest

      # Run Trivy Scan on AWS ECR Image
      - name: Run Trivy Scan on AWS ECR Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_NAME: scan-app
        run: trivy image $ECR_REGISTRY/$IMAGE_NAME:latest

      # Fail workflow if vulnerabilities are found
      - name: Fail workflow if vulnerabilities are found
        run: |
          trivy image --exit-code 1 --severity CRITICAL,HIGH 007kumar/scan-app:latest
          trivy image --exit-code 1 --severity CRITICAL,HIGH $ECR_REGISTRY/$IMAGE_NAME:latest
